name: rad
channels:
  - defaults
dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - absl-py
  - pyparsing
  - pillow
  - pip:
    - termcolor
    - git+git://github.com/deepmind/dm_control.git
    - git+git://github.com/1nadequacy/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - torchvision
    - scikit-image
    - tabulate
